export { default as Features} from './features/Features'
export { default as Footer} from './footer/Footer'
export { default as Header} from './header/Header'
export { default as News} from './news/News'
export { default as Services} from './services/Services'
export { default as Intro} from './intro/Intro'